name: hugo github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.2'

      - name: Build
        run: hugo --minify
      - name: Push changes to the repository
        run: |
         ls
         git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/g-savitha/g-savitha.github.io.git
         cp ./public/* g-savitha.github.io
         cd g-savitha.github.io
         ls
         git config user.email "${{ github.actor }}@users.noreply.github.com"
         git config user.name "${{ github.actor }}"        
         git add .
         git commit -am "Site updated"
         git push -f -q https://${{ secrets.GITHUB_TOKEN }}@github.com/g-savitha/g-savitha.github.io.git master
